### PR TITLE
fix: export private key

### LINKED ISSUE #23: Problem: Missing modal to export private key
Sub of:
- https://github.com/Ozean-L2/website/issues/533

If user logs in with social provider (inApp Wallet), they should be able to export their private key

### PR DESCRIPTION
**Pull request by teodorus-nathaniel**
resolves #23 

Fix: it needs to integrate message listener for the iframe to work
Docs: add how to use ExportPrivateKeyModal

Test: https://thirdweb-svelte-git-docs-export-clearpool.vercel.app/

## Summary by CodeRabbit

- **New Features**
	- Added installation instructions for the Svelte SDK and core thirdweb library.
	- Introduced detailed setup steps for integrating `ThirdwebSvelteProvider`.
	- New section for implementing `ConnectWalletModal` with code snippets.
	- Optional section for integrating `ExportPrivateKeyModal` with implementation examples.

- **Documentation**
	- Expanded development guidelines for setup, building, and testing.
	- Updated troubleshooting section with clearer instructions.
	- Minor formatting adjustments for consistency.

- **Enhancements**
	- Improved event handling in the `ExportPrivateKeyModal` component for better user experience.

### CODE REVIEW

**Comment by teodorus-nathaniel** [comment]
@pr-time-tracker bug commit [63fab43](https://github.com/holdex/thirdweb-svelte/pull/24/commits/63fab4366f69750f8de9968a3ab4a7b969b38dc6) && bug author @teodorus-nathaniel

**Comment by angelicawill** [comment]
@teodorus-nathaniel what was the bug in the previous PR? I'm confused because I tested it and it seems to work correctly

**Comment by teodorus-nathaniel** [comment]
> @teodorus-nathaniel what was the bug in the previous PR? I'm confused because I tested it and it seems to work correctly

yes, tbh I am pretty confused too because yesterday I think I tested and it works good too, but earlier, I tested it and it just doesn't work

you can try it in the pr #25, here: https://thirdweb-svelte-git-feat-home-clearpool.vercel.app/
it works for me in my brave browser, but doesn't work in my chrome 😅

**Comment by angelicawill** [comment]
@teodorus-nathaniel hmm, I tested in chrome and it worked this morning. But I just tested it and it doesn't work 😅

Thanks for explaining

**Comment by angelicawill** [comment]
Hmmm it still loads undefinitely...
https://github.com/user-attachments/assets/5387f216-819e-44c1-8730-d546d90f1c73 @teodorus-nathaniel

**Comment by teodorus-nathaniel** [comment]
> Hmmm it still loads undefinitely... https://github.com/user-attachments/assets/5387f216-819e-44c1-8730-d546d90f1c73 @teodorus-nathaniel

ah okay checking it again, I tested in my brave browser and it works good, but just tested in chrome and doesn't work too, checking it

**Pull request merged**
